const OpenAI = require('openai');

const openai = process.env.OPENAI_API_KEY
    ? new OpenAI({ apiKey: process.env.OPENAI_API_KEY })
    : null;

const SYSTEM_PROMPT = `You are V-PLATFORM Neural AI Agent — an autonomous cloud workspace assistant.
You can execute bash commands, read/write files, install packages, and deploy applications.
Respond with a JSON object containing your action. Available actions:
- {"type": "command", "cmd": "bash command to run"}
- {"type": "write", "path": "file/path", "content": "file content"}
- {"type": "read", "path": "file/path"}
- {"type": "response", "text": "your message to the user"}
- {"type": "multi", "steps": [array of action objects]}

Always use "multi" for complex tasks requiring multiple steps.
Be concise. Execute immediately.`;

async function processTask(task, context) {
    if (!openai) {
        return fallbackAgent(task, context);
    }
    try {
        const completion = await openai.chat.completions.create({
            model: 'gpt-4',
            messages: [
                { role: 'system', content: SYSTEM_PROMPT },
                { role: 'user', content: `Task: ${task}\n\nContext: ${JSON.stringify(context)}` }
            ],
            temperature: 0.1,
            response_format: { type: 'json_object' }
        });
        const result = JSON.parse(completion.choices[0].message.content || '{}');
        return result;
    } catch (err) {
        return fallbackAgent(task, context);
    }
}

function fallbackAgent(task, context) {
    const lower = task.toLowerCase();
    if (/install|setup/i.test(lower)) {
        const pkg = task.replace(/install|setup/gi, '').trim();
        return { type: 'multi', steps: [
            { type: 'command', cmd: `apt-get update -qq && apt-get install -y ${pkg || 'build-essential'} 2>&1 | tail -5` },
            { type: 'response', text: `Installing ${pkg || 'build-essential'}...` }
        ]};
    }
    if (/deploy|publish/i.test(lower)) {
        return { type: 'multi', steps: [
            { type: 'command', cmd: 'git add -A && git commit -m "Auto-deploy" && git push 2>&1' },
            { type: 'response', text: 'Deploying to production...' }
        ]};
    }
    if (/create|make|new|generate/i.test(lower)) {
        const project = task.replace(/create|make|new|generate|a |an |project|app/gi, '').trim();
        return { type: 'multi', steps: [
            { type: 'command', cmd: `mkdir -p "${project || 'new-project'}" && cd "${project || 'new-project'}" && git init` },
            { type: 'write', path: `${project || 'new-project'}/README.md`, content: `# ${project || 'New Project'}\n\nGenerated by V-PLATFORM Neural AI\n` },
            { type: 'response', text: `Created project "${project || 'new-project'}" with README` }
        ]};
    }
    if (/analyze|debug|check/i.test(lower)) {
        return { type: 'command', cmd: task };
    }
    return { type: 'command', cmd: task };
}

module.exports = { processTask };
